version: "3.7"
services:
  ################################################################################
  # container for database 
  database:
    image: mongo # get image from Docker repositories
    container_name: games-database
    environment:
      - MONGO_INITDB_DATABASE=games
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro # user creation script
      - ./database:/data/db # mongo stored databases
    ports:
      - "27017-27019:27017-27019" # 3 ports, first is main, other for replicas
    #networks:
    # Thus, the database will be isolated from the frontend calls
     # - backend-net
    #healthcheck:
     # test: ["CMD", "ps"]
      #interval: 5s
      #timeout: 10s
      #retries: 3
  ##################################################################################

    
